noun1 = input("Write a noun ")
verb1 = input("Write a verb ")
liquid = input("Write a kind of liquid ")
verb2 = input("Write a verb ending in '-ed' ")
noun2 = input("Write a noun ")
verb3 = input("Write a verb ending in '-ing/' ")
verb4 = input("Write a verb ")
adjective1 = input("Write an adjective ")
noun3 = input("Write a noun ")
adjective2 = input("Write an adjective ")
print ("Jack and Jill went up the", noun1)
print ("To", verb1, "a pail of", liquid)
print ("Jack", verb2, "down, and broke his", noun2)
print ("And Jill came", verb3, "after.")
print ("Then up Jack got and off did", verb4,)
print ("As", adjective1, "as he could caper,") 
print ("To old Dame Dob, who patched his ", noun3)
print ("With", noun2, "and", adjective2, "paper.")
